version: 2

builds:
  - id: bastion
    main: ./cmd/bastion
    binary: bastion
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: bastion
    builds:
      - bastion
    format: tar.gz
    name_template: "bastion_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: bastion
    repository:
      owner: LipJ01
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/LipJ01/fly-ssh-bastion
    description: CLI for SSH bastion tunnel management
    install: |
      bin.install "bastion"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
